In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.0+cu121


#Introductuon to Tensors
####Creating Tensors

In [ ]:
#scaler
scaler = torch.tensor(7)
scaler

tensor(7)

In [ ]:
scaler.ndim

0

In [ ]:
scaler.item()

7

In [ ]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
from re import M
#MATRIX
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

###RANDOM TESORS

In [ ]:
#Random TENSOR
random_tensor = torch.rand(3,3)
print(random_tensor)

tensor([[0.8535, 0.1397, 0.8286],
        [0.2336, 0.8751, 0.6843],
        [0.1411, 0.9530, 0.4477]])


In [ ]:
random_tensor.ndim

2

In [ ]:
#Random IMAGE TENSOR
random_tensor = torch.rand(244,244,3)
random_tensor.shape,random_tensor.ndim

(torch.Size([244, 244, 3]), 3)

##Zeors and Ones

In [ ]:
#Create  tensor of all zeors
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
#create tensor of all ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

## Creating a range of tensors and tensor_like

In [ ]:
#use torch range
two_to_10 = torch.arange(2,11,2)
two_to_10

tensor([ 2,  4,  6,  8, 10])

In [ ]:
#Creating tendor like
ten_zeros = torch.zeros_like(two_to_10)
ten_zeros

tensor([0, 0, 0, 0, 0])

##Tensor Datatype

In [ ]:
#Float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype = None,
                               device = None,
                               requires_grad = False)
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor = torch.tensor([3, 6, 9], dtype = torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
float_16_tensor * int_32_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

## Getting Information from tensor

In [ ]:
#create tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.5942, 0.1970, 0.5753, 0.6472],
        [0.6659, 0.6154, 0.2714, 0.7458],
        [0.4301, 0.8670, 0.4038, 0.5501]])

In [ ]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.5942, 0.1970, 0.5753, 0.6472],
        [0.6659, 0.6154, 0.2714, 0.7458],
        [0.4301, 0.8670, 0.4038, 0.5501]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


###Manipulating Tensors(tensor operation)

In [ ]:
#Create a Tensor
tensor = torch.tensor([1,2,3])
tensor * 10

tensor([10, 20, 30])

## Matrix Multiplication
 * Element wise multiplication
 * Matrix multiplicaiton

In [ ]:
#Element Wise multiplication
tensor
print(tensor * tensor)

tensor([1, 4, 9])


In [ ]:
#matrix Multiplication
torch.matmul(tensor,tensor)

tensor(14)

In [ ]:
torch.matmul(torch.rand(2,3),torch.rand(3,2)).shape

torch.Size([2, 2])

## One of the most common errors in deep learning : Shape Errors

In [ ]:
#shape for matrix multiplication
tensor_A =torch.tensor([[1,2],[3,4],[5,6]])
tensor_B = torch.tensor([[7,10,4],[8,11,5]])
torch.matmul(tensor_A,tensor_B)

tensor([[ 23,  32,  14],
        [ 53,  74,  32],
        [ 83, 116,  50]])

### Finding min, max, sum, etc

In [ ]:
x = torch.tensor([1,2,4,5,2,78,5,4,23,0])
x

tensor([ 1,  2,  4,  5,  2, 78,  5,  4, 23,  0])

In [ ]:
print(torch.max(x))
print(torch.min(x))
print(torch.sum(x))

tensor(78)
tensor(0)
tensor(124)


In [ ]:
#finding Positional mean and max
print('position of tensor having maximum value',torch.argmax(x))
print('position of tensor having minimum value',torch.argmin(x))

position of tensor having maximum value tensor(5)
position of tensor having minimum value tensor(9)


###  Reshaping, viewing and stacking

In [ ]:
#Lets create a tensor
x = torch.arange(1,9)
x ,x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8]), torch.Size([8]))

In [ ]:
x_reshaped = x.reshape(1,8)
x_reshaped,  x_reshaped.shape

(tensor([[5, 2, 5, 4, 5, 6, 5, 8]]), torch.Size([1, 8]))

### Change the view


In [ ]:
z = x.view(4,2)
z[:,0] = 5
z

tensor([[5, 2],
        [5, 4],
        [5, 6],
        [5, 8]])

In [ ]:
x , x.shape

(tensor([5, 2, 5, 4, 5, 6, 5, 8]), torch.Size([8]))

In [ ]:
# Stack tensors on top of rach other
x_stacked = torch.stack([x,x,x,x],dim = 1)
x_stacked

tensor([[5, 5, 5, 5],
        [2, 2, 2, 2],
        [5, 5, 5, 5],
        [4, 4, 4, 4],
        [5, 5, 5, 5],
        [6, 6, 6, 6],
        [5, 5, 5, 5],
        [8, 8, 8, 8]])

In [ ]:
##Squeeze and Unsqueeze
x_reshaped
x_reshaped.shape

torch.Size([1, 8])

In [ ]:
x_squezeed = x_reshaped.squeeze()
print(x_squezeed)

tensor([5, 2, 5, 4, 5, 6, 5, 8])


In [ ]:
x_unsquezed = x_squezeed.unsqueeze(dim = 0)
x_unsquezed

tensor([[5, 2, 5, 4, 5, 6, 5, 8]])

In [ ]:
# torch.permute - rearranges the dimension  of a target tensor in a specified order
torch_x = torch.rand(224,224,3)
torch_x.shape

torch.Size([224, 224, 3])

In [ ]:
torch_x_permuted = torch_x.permute(2,1,0)
torch_x_permuted.shape

torch.Size([3, 224, 224])

### Indexing with Pytorch

In [ ]:
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
#Let's index on our new tensor|
x[0,1,2]

tensor(6)

In [ ]:
x[0,2,2]

tensor(9)

In [ ]:
#You can use ':' to select all of a target dimension
x[:,:,:2]

tensor([[[1, 2],
         [4, 5],
         [7, 8]]])

In [ ]:
#Get all value of 0thn and 1s1t dimsnsion but only index 1 of second dimension
x[:, :, 1]

tensor([[2, 5, 8]])

## PYtorch tensors & Nuumpy array


In [1]:
#Numpy array to tensors
import torch
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [18]:
#Torch to numpy
x = torch.rand(1,2,3)
numpy_x = x.numpy()
x, x.dtype, numpy_x

(tensor([[[0.0701, 0.1650, 0.0413],
          [0.8128, 0.3661, 0.5930]]]),
 torch.float32,
 array([[[0.0700537 , 0.16500103, 0.04130918],
         [0.81278455, 0.3660946 , 0.5929514 ]]], dtype=float32))

In [4]:
#Change the value of array , what will this do to 'tensor'?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

## Pytorch reproducblity (trying to take random out of random)
* To reduce the randomness in neural networks in pytorch comes concept of  **random seed**
Essentially what random seed does is "flavour" the randomness

In [21]:
#create two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.7109, 0.8409, 0.8466, 0.1185],
        [0.1075, 0.4455, 0.5063, 0.8065],
        [0.9239, 0.4672, 0.0058, 0.9511]])
tensor([[0.3412, 0.7074, 0.3608, 0.7531],
        [0.0643, 0.4187, 0.0798, 0.5184],
        [0.4300, 0.1759, 0.3128, 0.3376]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [26]:
# Lets make some random but reproducable tensors
# set the random seed
random_seed = 32
torch.manual_seed(random_seed)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(random_seed)
random_tensor_D = torch.rand(3, 4)
print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8757, 0.2721, 0.4141, 0.7857],
        [0.1130, 0.5793, 0.6481, 0.0229],
        [0.5874, 0.3254, 0.9485, 0.5219]])
tensor([[0.8757, 0.2721, 0.4141, 0.7857],
        [0.1130, 0.5793, 0.6481, 0.0229],
        [0.5874, 0.3254, 0.9485, 0.5219]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Acessing a GPU

In [1]:
!nvidia-smi

Sat Nov 16 16:15:04 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   63C    P8              12W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

 ## Check for gpu access with Pytorch

In [3]:
import torch
torch.cuda.is_available()

True

In [6]:
#Setup a device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"

In [7]:
#count number of devices
torch.cuda.device_count()

1

## Putting tensors (and models) on the GPU


In [8]:
#Create a tensor(default on the cpu)
tensor = torch.tensor([1,2,3], device = "cpu")
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [10]:
#move tensor to the gpu if available
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

## Moving tensors back to the cpu

In [11]:
# if tensor is on GPU , can't transfrom it to Numpy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [12]:
#TO fix the GPU tensor with Numpy issue , we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])